### ISSUE TITLE
wiki/Setup-Phase is not working.

### ISSUE THREAD

**Issue by Hareramrai** [omniauth/omniauth#1006]
Please complete all sections.

### Configuration

- Provider Gem: `omniauth-google-oauth2`
- Ruby Version: `2.7.1`
- Framework: `Rails ~> 6.0.3`
- Platform: `MacOS`

### Expected Behavior

I am trying to set up provider credentials in real-time using`setup` action but it's never getting called.

```
#config/initializers/omniauth.rb

Rails.application.config.middleware.use OmniAuth::Builder do
  provider :google_oauth2, "GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET", setup: true
end

```

And inside routes, I have below code snippet.

```
 match '/auth/:provider/setup' => 'home#setup', via: [:get, :post]
```

And sample code for setup action in the home controller.

Setup action should be called and update the `request.env`. 

### Actual Behavior
Setup action is never getting called & I checked by putting byebug too. 

I am seeing multiple requests in the log for a single request. 

```
Started GET "/users/auth/google_oauth2" for 127.0.0.1 at 2020-08-13 21:52:55 +0530
I, [2020-08-13T21:52:55.721298 #95822]  INFO -- omniauth: (google_oauth2) Calling through to underlying application for setup.
I, [2020-08-13T21:52:55.721377 #95822]  INFO -- omniauth: (google_oauth2) Request phase initiated.
Started GET "/users/auth/google_oauth2" for 127.0.0.1 at 2020-08-13 21:52:55 +0530
I, [2020-08-13T21:52:55.955877 #95822]  INFO -- omniauth: (google_oauth2) Calling through to underlying application for setup.
I, [2020-08-13T21:52:55.955972 #95822]  INFO -- omniauth: (google_oauth2) Request phase initiated.
```

### Steps to Reproduce
Please see the sample code mentioned in the expected behavior part.

**Comment by BobbyMcWho** [comment]
Hey @Hareramrai, have you resolved this?
