### ISSUE TITLE
Is it possible to do client credentials flow for Microsoft Azure active directory with this library?

### ISSUE THREAD

**Issue by jeevanbalanmanoj** [omniauth/omniauth#1018]
Can this library be used to implement [client credentials flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow) for the azure active directory? If so please provide me with the samples or documentation on doing so
Please complete all sections.

### Configuration

- Provider Gem: `omniauth-*`
- Ruby Version: ``
- Framework: ``
- Platform: ``

### Expected Behavior

Tell us what should happen.

### Actual Behavior

Tell us what happens instead.

### Steps to Reproduce

Please list all steps to reproduce the issue.

**Comment by BobbyMcWho** [comment]
Sorry, I can't provide support on implementation with specific auth providers.

That being said, https://github.com/AzureAD/omniauth-azure-activedirectory may be of interest to you.

**Comment by jeevanbalanmanoj** [comment]
@BobbyMcWho  That repo is not supported anymore. Can you please confirm if omniauth can be used for client credentials flow in general irrespective of idp?

**Comment by BobbyMcWho** [comment]
It looks like it's just a normal OAuth2 Workflow, https://github.com/marknadig/omniauth-azure-oauth2 can be used for your reference, or you can build on top of https://github.com/omniauth/omniauth-oauth2, but again I cannot walk you through connecting to a specific auth provider.
