### ISSUE TITLE
OmniAuth 2.0.0 not work with omniauth-google-oauth2

### ISSUE THREAD

**Issue by shes50103** [omniauth/omniauth#1024]
### Configuration

- Provider Gem: `omniauth-2.0.0`
- Ruby Version: `2.6.5`
- Framework: `Rails 6.0.3.4`
- Platform: `MacOS`

### Expected Behavior

run `rails c` should enter console.

### Actual Behavior

run `rails c` end with

```
.rvm/gems/ruby-2.6.5/gems/devise-4.7.3/lib/devise/omniauth.rb:12:in `<main>': You are using an old OmniAuth version, please ensure you have 1.0.0.pr2 version or later installed.
```

### Steps to Reproduce

- `rails new new_project`
- add `omniauth` gem with version 2.0.0
- add `devise` gem (I use 4.7.3)
- add `omniauth-google-oauth2` gem (I use 0.8.1)
- run `rails generate devise:install`
- add config into `config/initializers/devise.rb`
 ```
config.omniauth :google_oauth2, ENV["google_app_id"], ENV["google_app_kdy"]
```

- run `rails c`

**Comment by shes50103** [comment]
I downgrade `omniauth` from 2.0.0 to 1.9.1 and it works.

**Comment by BobbyMcWho** [comment]
Devise is currently working to support omniauth 2.0, this is not an issue directly with this gem, but rather downstream consumers. 

https://github.com/heartcombo/devise/issues/5326
