### ISSUE TITLE
Developer provider not working under Rails 7.0.2.3

### ISSUE THREAD

**Issue by barttenbrinke** [omniauth/omniauth#1061]
Please complete all sections.

### Configuration

- Provider Gem: `omniauth-2.0.4`
- Ruby Version: `2.7.5`
- Framework: `rails 7.0.2.3`
- Platform: `ubuntu`

### Expected Behavior

Gemfile
```
gem 'omniauth'
gem "omniauth-rails_csrf_protection"
```

config/initializers/omniauth.rb
```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :developer
end
```

app/views/sessions/new.html.erb 
```
<%= form_tag('/auth/developer', method: 'post') do %>
  <button type='submit'>Login with Developer</button>
<% end %>
```

Clicking on `Login` should render the developer form and log you in using fake credentials.

### Actual Behavior

The only thing in the log is:
```
Started POST "/auth/developer" for 127.0.0.1 at 2022-03-21 21:58:57 +0100
D, [2022-03-21T21:58:57.950088 #3941647] DEBUG -- : (developer) Request phase initiated.
```

So the middleware is hit, but there is nothing after this.

### Steps to Reproduce

`gem install rails --version 7.0.2.3`
`rails new --css bootstrap`
Add the code in expected behaviour.
`bundle install`
`rails s`
`click Login`

**Comment by barttenbrinke** [comment]
I also am unable to get `omniauth-keycloak` to work in Rails 7, so that is probably related to omniauth having some issues with rails 7. My gut feeling is that it might be something to do with middleware handling, but I cannot put my finger on the root cause atm.

**Comment by barttenbrinke** [comment]
I think this might be the new turbo links being strange. Changed the view to:

```
<%= form_tag('/auth/developer', method: 'post', data: {turbo: false}) do %>
  <button type='submit'>Login with Developer</button>
<% end %>
```

Then that seems to work.

**Comment by BobbyMcWho** [comment]
@barttenbrinke glad you got it working, would you mind making a PR to the readme calling out this, and/or add to the wiki?

**Comment by barttenbrinke** [comment]
@BobbyMcWho The Readme is sort of lacking some valuable info :) I will look into it tomorrow.

**Comment by barttenbrinke** [comment]
@BobbyMcWho The PR is here ^^.

**Comment by masterkain** [comment]
I have an issue with the code proposed in the readme in a vanilla rails 7 app
https://github.com/omniauth/omniauth#rails-without-devise

I hit `http://0.0.0.0:3000/auth/developer` and this is the form:

```
<%= form_tag('/auth/developer', method: 'post', data: { turbo: false }) do %>
  <button type='submit'>Login with Developer</button>
<% end %>
```

I submit but:

```
DEBUG -- omniauth: (developer) Callback phase initiated.
ActionController::RoutingError (No route matches [POST] "/auth/developer/callback"):
```

for some reason omniauth callback calls the callback in POST, in the routes we have defined a `get`.
even if I switch to POST I get csrf issues.

**Comment by masterkain** [comment]
I proposed some further changes in the linked PR above, also putting back a `skip_before_action` that was there before the rewrite

**Comment by yshmarov** [comment]
I'd just like to add that you don't have to use a `form_tag`, you can just use a `button_to`:
```
<%= button_to "Sign in with Github", "/auth/github", data: { turbo: false } %>
```

**Comment by barttenbrinke** [comment]
> I proposed some further changes in the linked PR above, also putting back a `skip_before_action` that was there before the rewrite

The `skip_before_action` is no longer needed with the gem "omniauth-rails_csrf_protection" gem.

**Comment by dutow** [comment]
I'm also getting the same errors with the developer provider.

Looking at the source: https://github.com/omniauth/omniauth/blob/master/lib/omniauth/strategies/developer.rb#L38

The developer provider clearly creates a form that sends a POST request to the callback URL, without a CSRF token. How should this work without also allowing POST requests and disabling CSRF protection for create?

**Comment by barttenbrinke** [comment]
`gem "omniauth-rails_csrf_protection"` *should* take care of that.

**Comment by cycomachead** [comment]
Following the steps in the README, I am also running into this issue with the `:developer` provider. 

The csrf_proctection gem only handles validation of tokens, but the developer form does not have an authenticity token anywhere... 


My current solution is to do what other's have suggested, which is to skip verification on the `/callback`  route, but only in development. 

The OmniAuth developer form should probably include some authenticity token, though I'll be honest, I'm not immediately sure how to best do this... I'm not versed enough in the Rails internals to be able to generate an `authenticity_token` from within the omniauth middleware setup. 

I was exploring playing with a monkey patch, and it's not hard to find a spot to inject a new hidden field into the form. (This could be an option passed to the `provider` function. But I didn't have the time to figure out how to actually generate a token rails would accept. 

```rb
class OmniAuth::Strategies::Developer
  def request_phase
    token = '.....SOMETHING....'
    form = OmniAuth::Form.new(:title => 'User Info', url: '/auth/developer/callback')
    options.fields.each do |field|
      form.text_field field.to_s.capitalize.tr('_', ' '), field.to_s
    end
    form.html("\n<input type='hidden' name='authenticity_token' value='#{token}' />")
    form.button 'Sign In'
    form.to_response
  end
end
```

**Comment by spryffee** [comment]
Having the same issue. That would be great if it gets patched soon. @cycomachead thanks for the PR

**Comment by abartov** [comment]
Thank you @cycomachead for the patch!
