### ISSUE TITLE
Authentication failure because of _csrf_token on rails app

### ISSUE THREAD

**Issue by thebluber** [omniauth/omniauth#1063]
Please complete all sections.

### Configuration

- Provider Gem: `omniauth 2.0.4`, `omniauth_openid_connect`, `omniauth-linkedin-oauth2`, `omniauth-rails_csrf_protection`
- Ruby Version: `2.7.5`
- Framework: `rails 6.1.4.6`
- Platform: `macOS`

### Expected Behavior

The request validation phase succeeds with the correct given csrf token from session and request

### Actual Behavior
Users get an "OmniAuth::AuthenticityError, Forbidden" error in the request phase. 

`OmniAuth.config.request_validation_phase` is using `OmniAuth::AuthenticityTokenProtection` which is looking for the default key `:csrf` in the session. Rails apps are using the key `_csrf_token` instead. So because the key is missing in the session a random one is generated, thus the csrf tokens from session and the request do not match.

### Steps to Reproduce

- Create a rails app with `omniauth`, `omniauth-linkedin-oauth2`
- Configure linkedin oauth
- Add a button in rails app for linkedin login
- Click login and observe the logs

### My Workaround

I'm not sure whether I'm just doing things wrong. But since `omniauth-rails_csrf_protection` is used in my case which is hooked into `OmniAuth.config.before_request_phase` and it is doing exactly the same thing as `OmniAuth.config.request_validation_phase` just using the correct key for rails. I've manually set `OmniAuth.config.request_validation_phase = nil` in an initializer. And it started to work fine 🤷‍♀️ 

Is it supposed to work like that in rails?

**Comment by thebluber** [comment]
ah ok that was my misstake. Thanks :)

**Comment by inska** [comment]
I use omniauth-rails_csrf_protection gem, and csrf detected errors occurs not only development environment. Is there any way to skip check csrf? I'm using rails api.

**Comment by BobbyMcWho** [comment]
@inska can you open a new issue w/ an example app that reproduces your issue?
