### ISSUE TITLE
omniauth not OOTB compatible with rack_csrf

### ISSUE THREAD

**Issue by HoneyryderChuck** [omniauth/omniauth#1069]
Please complete all sections.

### Configuration

- Provider Gem: `omniauth-2.1.0`

### Expected Behavior

After upgrading `omniauth` to latest, this [example script](https://gitlab.com/honeyryderchuck/rodauth-oauth/-/blob/v0.9.1/examples/oidc/client_application.rb#L101) stopped working due to csrf verification failure, even after switching the CSRF backend to [rack_csrf](https://gitlab.com/honeyryderchuck/rodauth-oauth/-/blob/issue-55/examples/oidc/client_application.rb#L95). After some investigation I found out that the problem came from the backend used for csrf token verification [in rack-protection](https://github.com/sinatra/sinatra/issues/1778) not being compatible with  `rack_csrf`.

### Actual Behavior

While it's probably unreasonable to expect `rack-protection` to change default settings which may cause other software to break, perhaps it should be on `omniauth` side to document somewhere how to patch the `request_validation_phase` callback, at least for the most used CSRF backend outside of rails (which requires another full gem just to set the callback).

**Comment by BobbyMcWho** [comment]
If you'd like to add it to the wiki, it's open to contributions. While I do my best, I unfortunately can't account for every use case and framework, we try to be as framework agnostic as possible, so that's why Rails has a separate gem to help with setting it, since it's not entirely straightforward
