### ISSUE TITLE
Really confused about implementation

### ISSUE THREAD

**Issue by founder3000** [omniauth/omniauth#1073]
We're trying to use Oauth to authenticate users against their marketplaces. Unfortunately, the instructions are not clear. I'm probably just supposed to know what the doc writers mean, but I don't.
```
<%= form_tag('/auth/developer', method: 'post', data: {turbo: false}) do %>
  <button type='submit'>Login with Developer</button>
<% end %>
```
I guess "/auth/developer" is supposed to be "/<my controller name>/<my provider name>"? Is that correct? I wasn't clear on if Omniauth provided a route and controller called "auth" like in the example.

Also the route:

```
  get 'auth/:provider/callback', to: 'sessions#create'
```

Huh? Is :provider plugged in automatically by the middleware? Or am I supposed to know to substitute my provider name for :provider?

When I use the "/auth/developer" as the form url, obviously I get a "No route matches" error. If I use "/auth/<my provider name>" it tells me the same thing.

This is really, really confusing. Where is the middleware invoked where it would know to construct the url for my provider using my client id and secret? How is this supposed to work?

What is the form url REALLY supposed to be?

************ UPDATE ************

I see that omniauth is supposed to add 'auth' routes by default? But it hasn't, as now I'm faced with 'uninitialized constant AuthController'.

This seems like a gem that is easily used by people that already know how to use it, if that makes any sense. When I write documentation, usually I have assumptions in there that I don't realize that others don't know, and I guess that's the case here. I did find an issue where downgrading to 1.9.1 is supposed to fix the "uninitialized constant AuthController" but that doesn't work either. This is a heartbreaker, I have 24 hours into this already and I'm no further ahead than when I started.

**Comment by BobbyMcWho** [comment]
Have you followed every step in the readme?
![image](https://user-images.githubusercontent.com/6934825/171967724-a3f7d695-a661-463b-a965-82248df559ef.png)

It calls out that you need to create a session controller as well as have a way to manage your sessions. A lot of folks use Devise for the latter portion. I apologize that you've not been able to get it up and running, however I believe that everything that's needed to get a rails app working w/ devise is included in the Readme

**Comment by BobbyMcWho** [comment]
If you'd like to use devise, they have detailed instructions [here](https://github.com/heartcombo/devise/wiki/OmniAuth:-Overview)

**Comment by BobbyMcWho** [comment]
Here's a rails app in a single file that has a functioning omniauth install https://github.com/BobbyMcWho/omniauth_2_examples/blob/main/rails_app_with_csrf_gem.ru

**Comment by founder3000** [comment]
Thank you so much for the reply. I was mixed up with versions 1.9 and 2.0 and the get/post differences between the two, and finally got past that. Working against a provider that does not allow localhost addresses for test has been another hurdle but we'll set up the domain and certificate. Thanks again!
