### ISSUE TITLE
Feature Request: sign in with Ethereum

### ISSUE THREAD

**Issue by chrishobcroft** [omniauth/omniauth#1078]
# Use case

As a user of web applications using omniauth, I would like to be able to sign in with Ethereum.

# More details

For more details, see login.xyz and https://github.com/openstreetmap/openstreetmap-website/issues/3582

**Comment by BobbyMcWho** [comment]
I won't implement this, specific login implementations are handled in provider specific strategies coded in separate gems/repos.

**Comment by chrishobcroft** [comment]
Hey @BobbyMcWho please re-open this. Perhaps someone else can make it as a contribution to this project?

There's even an existing implementation in Ruby: https://github.com/spruceid/siwe-ruby which is perhaps the "providers specific strategy"?

**Comment by BobbyMcWho** [comment]
@chrishobcroft this repo's issues are not a place to request new strategies. 

If one of the [existing strategies](https://github.com/omniauth/omniauth/wiki/List-of-Strategies) doesn't suit your needs, then you need to either write one yourself, or contract a developer to do it for you. 

What you're asking is not an insignificant amount of work, and I've already stated that this repo is not the proper place to add that sort of functionality to.
