### ISSUE TITLE
Programatically invoke an omniauth strategy 

### ISSUE THREAD

**Issue by rockwellll** [omniauth/omniauth#1082]
Please complete all sections.

### Configuration

- Provider Gem:  none
- Ruby Version: 3.1.2
- Framework: Rails
- Platform: Ruby

### Expected Behavior

My usecase is a bit weird. So, we're not building a "Login Via xxx" page. Rather, a logged in person, can integrate multiple 3rd party tools. So, i first want to ensure that the user performing the operation can perform the operation(add a new integration).
So, i have a controller that validates using `pundit` gem. But, i could not figure out how to call the strategy inside the controller.

What i want to do is

```
def new
   # validation 
    
   OmniAuth::Strategies::Provider.new(Rails.application).call request.env 
end
```

and the strategy then doing it's work. with redirection, etc.

Is this possible?

Thanks

**Comment by rockwellll** [comment]
I have overidden `on_path?` method. Is this correct?

```ruby
      def on_path?(path)
        current_user = env["warden"].user

        if (business = Business.find_by_handle(current_path.split("/").compact_blank.first))
          current_user.privileges.find_by(business:).owner? || current_user.privileges.find_by(business:).administrator?
        else
          false
        end
      end

```

**Comment by BobbyMcWho** [comment]
You may want to write something yourself using the [oauth2](https://rubygems.org/gems/oauth2/versions/1.2.0) gem, while you may be able to override stuff in omniauth to get this to work, I can't provide any guidance as to what you would need to override nor the workflow that you'd need.

**Comment by rockwellll** [comment]
Thanks for your comment. What do you think on the code i wrote in https://github.com/omniauth/omniauth/issues/1082#issuecomment-1196762904. I understand that i need to also override `on_callback_path?` to ensure that works as well.
