### ISSUE TITLE
Compatibility issues with rack-protection 3.x

### ISSUE THREAD

**Issue by deepfryed** [omniauth/omniauth#1089]
Please complete all sections.

### Configuration

- Provider Gem: `omniauth`
- Ruby Version: `3.1.2`
- Framework: `N/A`
- Platform: `Linux`

### Expected Behavior

The library should load

### Actual Behavior

load error, 'rack-protection' not found

### Steps to Reproduce

Setup a ruby or rails app with rack-protection 3.x. The file 'rack-protection.rb' has been renamed to 'rack_protection.rb' in sinatra.

**Comment by BobbyMcWho** [comment]
Hi, it appears that Sinatra has merged a fix to keep backwards compatibility

**Comment by BobbyMcWho** [comment]
If they haven't cut a release, you could point your gem version at their master sha

**Comment by BobbyMcWho** [comment]
Looks like 3.0.1 was pushed 3 minutes ago

**Comment by biologistbrian** [comment]
Yeehaw! just saw that. yay!
