### ISSUE TITLE
why user_response_structure's image have no effect

### ISSUE THREAD

**Issue by melon0803** [omniauth/omniauth#1111]
Please complete all sections.

### Configuration

- Provider Gem: `omniauth-oauth2_generic`
- Ruby Version: ``
- Framework: ``
- Platform: ``

### Expected Behavior

Tell us what should happen.
gitlab can synchronize user profile picture by image tag in user_response_structure's params
### Actual Behavior
Tell us what happens instead.
image tag have no effect

### Steps to Reproduce

Please list all steps to reproduce the issue.

```
gitlab_rails['omniauth_providers'] = [
   {
     "name": "oauth2_generic",
     "label": "ECMP", #optional label for login button, defaults to "Oauth2 Generic"
     "app_id": "Gitlab",
     "app_secret": "1JhjYGTmCeKR",
     "args": { 
       "client_options": {
         "site":"http://192.168.66.147:4000",
         "user_info_url":"/v1/auth/detail",
         "authorize_url":"/v1/oauth/authorize",
         "token_url":"/v1/oauth/token"
       },
       "user_response_structure":{
         "root_path":["data"],
         "id_path":["data", "id"],
         "attributes":{
            name: "realName",
 		    username: "username",
           email: "email",
          image: "image",
         }
       },
       "authorize_params":{
         "scope":"all"
       },
       "strategy_class":"OmniAuth::Strategies::OAuth2Generic"
    }
   }
]
```

**Comment by melon0803** [comment]
gitlab_rails['omniauth_enabled'] = true
# gitlab_rails['omniauth_allow_single_sign_on'] = ['saml']
gitlab_rails['omniauth_allow_single_sign_on'] = ['oauth2_generic']
gitlab_rails['omniauth_sync_profile_attributes'] = ['name', 'username', 'email', 'image']
gitlab_rails['omniauth_sync_email_from_provider'] = 'oauth2_generic'
gitlab_rails['omniauth_sync_image_from_provider'] = 'oauth2_generic'
gitlab_rails['omniauth_sync_profile_from_provider'] = ['oauth2_generic']
# gitlab_rails['omniauth_sync_profile_attributes'] = ['email']
# gitlab_rails['omniauth_auto_sign_in_with_provider'] = 'saml'
# gitlab_rails['omniauth_block_auto_created_users'] = true
gitlab_rails['omniauth_block_auto_created_users'] = false

**Comment by melon0803** [comment]
```
gitlab_rails['omniauth_enabled'] = true
# gitlab_rails['omniauth_allow_single_sign_on'] = ['saml']
gitlab_rails['omniauth_allow_single_sign_on'] = ['oauth2_generic']
gitlab_rails['omniauth_sync_profile_attributes'] = ['name', 'username', 'email', 'image']
gitlab_rails['omniauth_sync_email_from_provider'] = 'oauth2_generic'
gitlab_rails['omniauth_sync_image_from_provider'] = 'oauth2_generic'
gitlab_rails['omniauth_sync_profile_from_provider'] = ['oauth2_generic']
# gitlab_rails['omniauth_sync_profile_attributes'] = ['email']
# gitlab_rails['omniauth_auto_sign_in_with_provider'] = 'saml'
# gitlab_rails['omniauth_block_auto_created_users'] = true
gitlab_rails['omniauth_block_auto_created_users'] = false
```

**Comment by BobbyMcWho** [comment]
This is a GitLab config question not directly an omniauth question. You may try asking in GitLab forums
