### ISSUE TITLE
Need to update rack configuration from 2.2.3 to 2.2.3.1

### ISSUE THREAD

**Issue by Quitehours** [omniauth/omniauth#1115]
Defectdojo found critical vulnerabilities 
![image](https://github.com/omniauth/omniauth/assets/54599310/5369e222-3034-4264-abf3-87e35b2dd329)

![image](https://github.com/omniauth/omniauth/assets/54599310/3bbb03dd-1119-4dee-8451-6bdb18402b58)

**Comment by BobbyMcWho** [comment]
OmniAuth does not specify a specific version of rack, only greater than a certain version. Update rack to whatever version you want.

```ruby
spec.add_dependency 'rack', '>= 2.2.3'
```
