### ISSUE TITLE
Support passing a redirect URL to facebook on authentication in callback

### ISSUE THREAD

**Issue by kbighorse** [omniauth/omniauth#218]
I'd like to require Facebook authentication dynamically, i.e. not for its own sake but in the course of making another specific request.  I know Facebook will append parameters it receives to the  callback, just need Omniauth to support sending the parameters in the first place.  This way I can redirect to the original destination while requiring Facebook authentication 'along the way'.  I'm happy to implement this if someone can point me in the right direction.

Example:

http://app.com/auth/facebook?next=/view_fb_friends

<get connected with facebook>

http://app.com/auth/facebook/callback?code=XXX&next=/view_fb_friends

<create authentication>

http://app.com/view_fb_friends

Kimball

**Comment by jahrichie** [comment]
What version is this in?  These are query params yes? /login?origin=http://foo.bar/thing/220 ?
