### ISSUE TITLE
request.env['omniauth.origin'] returning nil during callback.

### ISSUE THREAD

**Issue by dustmoo** [omniauth/omniauth#306]
When trying to access the request.env['omniauth.origin'] param I end up with a nil result during the call back. This has also been reported here(by another user):

http://groups.google.com/group/omniauth/browse_thread/thread/ffff2cc80f0e559e

Help would be appreciated.

Thanks.

**Comment by 1campbellj** [comment]
@spitza Using the ?origin param in the URL fixed the issue for me.

**Comment by ryanicle** [comment]
I have the same problem with request.env["omniauth.origin"] returns nil. Tried to set the param and it does not work either. Any solutions? Thanks!

**Comment by edivandecastro** [comment]
I have the same problem with request.env["omniauth.origin"] returns nil. Tried to set the param and it does not work either. Any solutions? Thanks!

**Comment by jamesfzhang** [comment]
`request.env['omniauth.origin']` returns `nil` if the user is new. I'm guessing the value is getting lost through the user sign up process. If the user already exists in the database and is just logging in, the value is correct.

Does anyone have a fix for this? It's a pretty big bug...

**Comment by SirRawlins** [comment]
+1 on this issue when using 1.3.1.

I've attempted to use the workaround suggested by @spitza however it doesn't appear to have made much difference for me.

**Comment by fippu82** [comment]
Could it be that it works only when using `sign_in_and_redirect `but not when just using `sign_in `method? in the OmniauthCallbacksController, if that makes any sense. 
I have to execute custom code after signing in the user and found no better way than doing it in the said controller, and in the end redirect by myself. Then I'm facing the  problem described in this issue.

**Comment by fippu82** [comment]
This works for me on 1.3.1 when passing the redirect URL via `origin `parameter, also for new users.

**Comment by mdepolli** [comment]
Seems to work by default on 1.4.2 over OAuth2. Not even necessary to manually pass the origin as a query param.

**Comment by tmilewski** [comment]
This seems to be working as of late. As such I'm going to close it. Should this still be a problem, please feel free to reopen the issue.

**Comment by dachinat** [comment]
I can't get it to work on `Rails 5.2.0` + `omniauth (1.8.1)`

**Comment by dachinat** [comment]
Never mind. It turns out that I have to still fully enable sessions for omniauth.
