### ISSUE TITLE
extra request parameters in authorization phase

### ISSUE THREAD

**Issue by tompata** [omniauth/omniauth#390]
I'm using oauth with Facebook provider, and i would like to redirect the user by device: mobile / desktop view.
Facebook supports different views by "display" parameter, example:
http://www.facebook.com/dialog/oauth?client_id=YOUR_APP_ID&redirect_uri=YOUR_URL&display=touch

The problem is, that i cannot add this extra "display" parameter to the request string, because there's no such method in Oauth.
I've found a method: "request_phase", but it works only from configuration options.
It would be useful to add request parameters too.

**Comment by aprescott** [comment]
I realise this is a fairly old issue, but it's prominent on Google, so I thought it would be useful to include another way of tackling this.

You can override `authorize_params` for a particular strategy to include params that should be allowed through to the authorize URL:

```ruby
module OmniAuth
  module Strategies
    class FooBar < OmniAuth::Strategies::OAuth2
      option :name, "foo_bar"

      option :client_options, {
        # ...
      }

      uid do
        # ...
      end

      info do
        {
          # ...
        }
      end

      extra do
        {
          # ...
        }
      end

      def authorize_params
        super.merge(foo_param: request.params["foo_param"], bar_param: request.params["bar_param"])
      end
    end
  end
end
```

This will allow `foo_param=` and `bar_param=` through.
