### ISSUE TITLE
failure?message=invalid_credentials with google apps

### ISSUE THREAD

**Issue by davidfabreguette** [omniauth/omniauth#418]
Hi,
I've been trying to use omniauth with google apps. The purpose is to allow users to log in my application through loggin in with a basic gmail account.

I added the omniauth gem and here's what's in my omniauth.rb file :

Rails.application.config.middleware.use OmniAuth::Builder do
  require 'omniauth/openid'
  require 'oa-oauth'
  provider :openid, nil, :name => 'google', :identifier => 'https://www.google.com/accounts/o8/id'
end

I keep having the same url error "failure?message=invalid_credentials" when I type in the url "/auth/google" even though i'm signed in with my gmail account.

Here's what's in my rails console : 
"Generated checkid_setup request to https://www.google.com/accounts/o8/ud with assocication AOQobUfJQwJjqPgLuOxYDg3ZQE3D2NHrUsHpH2YyAACnTIn2Ak3WcvG2
Error attempting to use stored discovery information: OpenID::TypeURIMismatch
Attempting discovery to verify endpoint
Performing discovery on https://www.google.com/accounts/o8/id?id=AItOawmZjED4CBboUKUhjjMOlV4HgJNMgkb5J4U
Using 'check_authentication' with https://www.google.com/accounts/o8/ud"

My project is on github : https://davidfabreguette@github.com/davidfabreguette/PhoneLog2.git 

Thanks for any help you could bring :)

**Comment by glafir** [comment]
But I have my project in Interner and I get this message (((
You can not log in as Google Oauth2, because "Invalid credentials".
