### ISSUE TITLE
Support Logging

### ISSUE THREAD

**Issue by mbleigh** [omniauth/omniauth#583]
OmniAuth should have a logger accessible at `OmniAuth.logger`. This logger should probably just point at STDOUT by default but should be easily settable in, for instance, a Rails app like so:

``` ruby
OmniAuth.config.logger = Rails.logger
```

**Comment by franklingu** [comment]
I am using omniauth 1.2.2. Although I put ```OmniAuth.config.logger = Rails.logger``` but it still prints output to console. And once I turn off console, omniauth cannot work anymore

**Comment by wpp** [comment]
5 years later, still relevant and much appreciated: Thank you @lpsBetty! 👍

**Comment by zackfrank** [comment]
...and 3 years later than that!

**Comment by onomojo** [comment]
...and 5 years later than that!
