### ISSUE TITLE
"omniauth.params" are lost in Test Mode

### ISSUE THREAD

**Issue by isaacsanders** [omniauth/omniauth#631]
In my test environment, when I try to access data in the omniauth.params hash, I find that I have an empty hash.

I would expect the params to behave as in my development environment, and to not be lost.

I am on Rails 3.2.8, Devise 2.1.2, and OmniAuth 1.1.0.

I am happy to supply any information that I can.

**Comment by arefaslani** [comment]
I'm using Omniauth 1.8.1 and still have this problem.

**Comment by andyklimczak** [comment]
query string was removed from the mock redirect url in this commit: https://github.com/omniauth/omniauth/commit/e2f2dce9748a9eab5d62b692fbceccbed4bf0f9f#diff-e4a65aeb02719e02950ffed620b8e06eL277
