### ISSUE TITLE
Rails 4 session values not persisting after redirect

### ISSUE THREAD

**Issue by beerlington** [omniauth/omniauth#670]
I'm having [an issue ](http://stackoverflow.com/questions/15351985/session-not-persisting-across-redirect-with-omniauth-and-rails-4) where session values that I set in the SessionsController are not persisted when users are redirected to a different page.

In the following controller, I am setting the user_id and redirecting to a different controller's action. When execution gets to that controller, the value I previously set is no longer available. Similar logic works in a Rails 3.2 application so I'm not sure if it's a problem with OmniAuth or what.

``` ruby
class SessionsController < ApplicationController
  skip_before_filter :authenticate_user!

  def create
    user = User.find_or_create_by_auth_hash(auth_hash)
    session[:user_id] = user.id
    redirect_to root_path
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end

end
```

**Comment by jlkwarteng** [comment]
Currently Experiencing the very same issue. Although i'm not working with omniauth session variables i set do not persist to the next controller on redirect in rails
