### ISSUE TITLE
OmniAuth.config.mock_auth falls back to default with :stripe_connect

### ISSUE THREAD

**Issue by dylandrop** [omniauth/omniauth#696]
For some reason, when I add 

```
  def set_omniauth_for provider
    OmniAuth.config.mock_auth[provider] = {
      provider: provider.to_s,
      uid: "1234",
      credentials: {
        token: "my_token",
        secret: "my_secret"
      }
    }
  end
```

OmniAuth still falls back to using my default provider (Facebook) in test, instead of using `:stripe_connect` when I pass that to this method. If I inspect `request.env["omniauth.auth"], I get

```
{"provider"=>"default", "uid"=>"1234", "info"=>{"name"=>"Bob Example"}}
```

However, if I inspect the `OmniAuth.config.mock_auth[:stripe_connect]` this returns 

`{:provider=>'stripe_connect',
 :uid=>"1234",
 :credentials=>{:token=>"my_token", :secret=>"my_secret"}}`

 as expected.

Using Rails 3.2.11 and omniauth-1.1.4

**Comment by benpolinsky** [comment]
+1

**Comment by dylandrop** [comment]
Don't remember, 2 years ago sorry :/

**Comment by benpolinsky** [comment]
Thought I'd ask :) thanks

**Comment by whatcould** [comment]
Just a note that I couldn't get this to break in the same way no matter what I tried. [omniauth-stripe-connect (2.4.0), omniauth (1.2.2)]

One thought is that set_omniauth_for(provider) method above doesn't use OmniAuth::AuthHash; the current OmniAuth docs use this for the mock_auth:

```ruby
OmniAuth.config.mock_auth[:stripe_connect] = OmniAuth::AuthHash.new({  ...
```

**Comment by jedrekdomanski** [comment]
Same problem here. Was anyone able to resolve this problem?

**Comment by jedrekdomanski** [comment]
I got it!
```ruby
#config/environments/test.rb
OmniAuth.config.test_mode = true
  OmniAuth.config.mock_auth[:github] = OmniAuth::AuthHash.new({
      'provider' => 'github',
      'uid' => '123545',
      'info' => {
        'name' => 'mockuser',
        'image' => 'mockuser_avatar_url'
      }
    })
```
