### ISSUE TITLE
What to do when Authorize and Token reside on different domains?

### ISSUE THREAD

**Issue by jlebrech** [omniauth/omniauth#708]
I have a site I have to connect to which has http://example.com/oauth2/authorize for authorize url and http://api.example.com/oauth2/token for token url.

this wont work will it?

```
  option :client_options, {
    site: 'http://example.com',
    authorize_path: "/oauth2/authorize.php",
    token_url: '/oauth2/token.php'
  }
```

**Comment by naps62** [comment]
I'm also suffering with this right now? Is this even possible?
I realize it's probably a mistake on the provider's part, but that's not really up to me

I'm trying to mess around the code to work around this, but I'd like to know if there's an easy alternative

**Comment by tmilewski** [comment]
Generally speaking, providers won't let you call back to a different URL for security reasons.

Considering that this issue is almost two years old, I'm going to close for now. Feel free to re-open should you need to follow-up.
