### ISSUE TITLE
Refresh_token is not available

### ISSUE THREAD

**Issue by dja** [omniauth/omniauth#714]
I'm trying to write my own strategy based on the OmniAuth Dropbox and AngelList strategies for the Square Connect API, and everything should be the same, but I'm getting an error that a refresh_token is not available.

Neither of the other services require refresh tokens, or provide them, so I don't know how I'm getting this error, except that it is calling into the Oauth2 gem's 'refresh!' method.

Any takers?

**Comment by tmilewski** [comment]
This would be an issue for the `oauth2` gem.

Considering that this issue is over three years old, I'm going to close for now. Feel free to re-open should you need to follow-up.
