### ISSUE TITLE
Omniauth + Devise + Rails 4: strategy.rb:143:in `initialize': Received wrong number of arguments. [“google_apps”] (ArgumentError)

### ISSUE THREAD

**Issue by andytriboletti** [omniauth/omniauth#717]
I'm upgrading my Rails app from 3.1.3 to 4.0.2. In order to do that I need to upgrade devise and omniauth too.

I had these gems in my Gemfile:

gem 'rails', '3.1.3'
gem 'devise', '1.4.9'
gem 'omniauth', '0.3.2'
gem 'oa-openid'
I changed them to:

gem 'rails', '4.0.2'
gem 'devise'
gem 'omniauth'
gem 'oa-openid'
When I start my rails server I get this traceback.

/Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/omniauth-1.1.4/lib/omniauth/strategy.rb:143:ininitialize': Received wrong number of arguments. ["google_apps"](ArgumentError) from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/oa-openid-0.3.2/lib/omniauth/strategies/open_id.rb:39:ininitialize' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/oa-openid-0.3.2/lib/omniauth/strategies/google_apps.rb:8:in initialize' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/actionpack-4.0.2/lib/action_dispatch/middleware/stack.rb:43:innew' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/actionpack-4.0.2/lib/action_dispatch/middleware/stack.rb:43:in build' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/actionpack-4.0.2/lib/action_dispatch/middleware/stack.rb:118:inblock in build' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/actionpack-4.0.2/lib/action_dispatch/middleware/stack.rb:118:in each' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/actionpack-4.0.2/lib/action_dispatch/middleware/stack.rb:118:ininject' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/actionpack-4.0.2/lib/action_dispatch/middleware/stack.rb:118:in build' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/railties-4.0.2/lib/rails/engine.rb:495:inapp' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/railties-4.0.2/lib/rails/application/finisher.rb:34:in block in module:Finisher' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/railties-4.0.2/lib/rails/initializable.rb:30:ininstance_exec' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/railties-4.0.2/lib/rails/initializable.rb:30:in run' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/railties-4.0.2/lib/rails/initializable.rb:55:inblock in run_initializers' from /Users/andy/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/tsort.rb:150:in block in tsort_each' from /Users/andy/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/tsort.rb:183:inblock (2 levels) in each_strongly_connected_component' from /Users/andy/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/tsort.rb:219:in each_strongly_connected_component_from' from /Users/andy/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/tsort.rb:182:inblock in each_strongly_connected_component' from /Users/andy/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/tsort.rb:180:in each' from /Users/andy/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/tsort.rb:180:ineach_strongly_connected_component' from /Users/andy/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/tsort.rb:148:in tsort_each' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/railties-4.0.2/lib/rails/initializable.rb:54:inrun_initializers' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/railties-4.0.2/lib/rails/application.rb:215:in initialize!' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/railties-4.0.2/lib/rails/railtie/configurable.rb:30:inmethod_missing' from /Users/andy/heroku/selfiemarket/config/environment.rb:5:in <top (required)>' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:inrequire' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in block in require' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:inload_dependency' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in require' from /Users/andy/heroku/selfiemarket/config.ru:3:inblock in ' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/rack-1.5.2/lib/rack/builder.rb:55:in instance_eval' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/rack-1.5.2/lib/rack/builder.rb:55:ininitialize' from /Users/andy/heroku/selfiemarket/config.ru:in new' from /Users/andy/heroku/selfiemarket/config.ru:in' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/rack-1.5.2/lib/rack/builder.rb:49:in eval' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/rack-1.5.2/lib/rack/builder.rb:49:innew_from_string' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/rack-1.5.2/lib/rack/builder.rb:40:in parse_file' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/rack-1.5.2/lib/rack/server.rb:277:inbuild_app_and_options_from_config' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/rack-1.5.2/lib/rack/server.rb:199:in app' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/railties-4.0.2/lib/rails/commands/server.rb:48:inapp' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/rack-1.5.2/lib/rack/server.rb:314:in wrapped_app' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/railties-4.0.2/lib/rails/commands/server.rb:75:instart' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/railties-4.0.2/lib/rails/commands.rb:76:in block in <top (required)>' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/railties-4.0.2/lib/rails/commands.rb:71:intap' from /Users/andy/.rvm/gems/ruby-1.9.3-p362/gems/railties-4.0.2/lib/rails/commands.rb:71:in <top (required)>' from script/rails:6:inrequire' from script/rails:6:in `'

In config/initiailizers/devise.rb I had this line:

config.omniauth :google_apps, OpenID::Store::Filesystem.new('./tmp'), :domain => 'gmail.com'
I changed it to:

config.omniauth :google_apps, :store => OpenID::Store::Filesystem.new('/tmp'), :domain => 'gmail.com'
I still get the error.

I originally used this example project to setup my Omniauth and Devise app https://github.com/holden/devise-omniauth-example

I posted this question on Stackoverflow too
http://stackoverflow.com/questions/20806719/omniauth-devise-rails-4-strategy-rb143in-initialize-received-wrong-num

**Comment by chris-ma** [comment]
Hi Andy,

I've recently had to implement omni-auth + devise as a project. 

I think from what I can see is that the wrong attributes have been declared inside your user model. There's been some changes between Rails 3 to Rails 4, one of which are strong params. Make sure you remove the attr_accessible inside your user model as you wont need them and declare the correct attributes inside your strong params located in your controller.

**Comment by tmilewski** [comment]
☝️ 

Considering that this issue is over three years old, I'm going to close for now. Feel free to re-open should you need to follow-up.
