### ISSUE TITLE
OMNIAUTH_ORIGIN empty

### ISSUE THREAD

**Issue by canujohann** [omniauth/omniauth#721]
Hi,

Thank you for this plugin. I've implemented it in my website and it works (almost) perfectly. Sometimes, OMNIAUTH_ORIGIN  in the callback is nil.

agent info are as below : 

---

HTTP_USER_AGENT Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.102 Safari/537.36

---

Is this a bug or just a browser issue ?

Thank you !

**Comment by tmilewski** [comment]
Closing in favor of #306
