### ISSUE TITLE
OAuth Mandrill

### ISSUE THREAD

**Issue by maxime-d** [omniauth/omniauth#723]
I would want integrate Mandrill connection in our solution with OAuth. I followed a instructions for build application on Mandrill UI, but Mandrill give only client ID, without client SECRET.

So, I try to define a provider in OmniAuth::Builderbut it doesn't works. My question is, do you think is possible to use OmniAuth authentication system for Mandrill OAuth (which not delivery client SECRET) ?

Thanks

**Comment by joepasq** [comment]
What instructions were you following? On Mandrill's [knowledge base](https://mandrill.zendesk.com/hc/en-us/search?utf8=✓&query=auth&commit=Search), I do not see indication that they are an OAuth provider. Across their general documentation, the [only result for 'auth'](http://mandrillapp.com/docs/?_ga=1.242355074.1663356502.1421448225#stq=auth&stp=1) are web hooks documents. 

(If you’re using [SMTP, any valid API key](https://mandrill.zendesk.com/hc/en-us/articles/205582127-Using-Mandrill-s-SMTP-integration-with-Web-Frameworks) is a password.)

**Comment by tmilewski** [comment]
Yeah, @joepasq is correct. It doesn't appear that Mandrill is an OAuth provider.
