### ISSUE TITLE
wrong request.env ['omniauth.auth']

### ISSUE THREAD

**Issue by FreddySerg** [omniauth/omniauth#728]
The bottom line is that the authorization through facebook, twitter, linkedin in CallbacksController in request.env ['omniauth.auth'] comes only uid and provider, no additional informations extra, credentials, etc. . And it does not happen every time, multiple requests can be valid, and then randomly get a hash with only two parameters. Does anyone know what the problem is and how to solve it?

devise (3.2.3) omniauth (1.2.1) omniauth-oauth2 (1.1.2) oauth2 (0.9.3)

**Comment by tmilewski** [comment]
A lot has changed since this was first submitted and thus I'm going to close it. Should this still be a problem, please feel free to reopen the issue.
