### ISSUE TITLE
How to see whats sent to Oauth provider?

### ISSUE THREAD

**Issue by hakunin** [omniauth/omniauth#739]
Hi, I am stuck on `redirect_uri_mismatch` from MailChimp, even though the paths should match.

It would help greatly to be able to see what is exactly sent to the Oauth provider so I can debug.

How can I do that?

I tried dumping the redirect here

```
module OmniAuth::Strategy
  def request_call
    #...
    p request
    #...
```

But that doesn't seem to have any request info and looks more like a callback, since it includes the error already and can't find where to plug in to print the call to provider.

Many thanks for any help.

**Comment by tmilewski** [comment]
What's sent *to* the OAuth provider should be available in the URL as GET params.

Requesting additional information about a user, after receiving tokens, is up to the individual provider gems. The only catch-all response that I could provide would be the same as @scrawlon's approach above.
