### ISSUE TITLE
Session changing after omniauth redirect

### ISSUE THREAD

**Issue by auser** [omniauth/omniauth#741]
I'm using rails 4 + devise + omniauth. When we're redirecting a user with omniauth, the `session['session_id']` is changed from the time of the request to the omniauth direct and into the callback phase.

The redirect_phase gets a session_id of `7409e4fc059f39c20ff93898ab53a409`
The callback_phase gets a session_id of `387135938e837e5f601e7d56f2b62bc0`

My app controller has the following line...

``` ruby
class ApplicationController < ActionController::Base
    protect_from_forgery with: :reset_session, :if => Proc.new { |c| c.request.format.include?('application/json') }
    # ...
```

Has anyone else run into this?

**Comment by tmilewski** [comment]
Considering that this issue is almost two and a half years old, I'm going to close for now. Feel free to re-open should you need to follow-up.
