### ISSUE TITLE
Callback path isn't aware of sub-directory placement

### ISSUE THREAD

**Issue by btrepp** [omniauth/omniauth#753]
I'm using rails 4 and omniauth-ldap,deploying with warbler in glassfish. Looking through the source its grabbing callback_path from omniauth core.

For some reason the rest of the rails app works fine, even the login pages, but the callback URL is going to the root of the webserver, this conflicts with how glassfish is deploying the applications.

http://glassfishserver/application/users/auth/ldap is the form. This posts to
http://glassfishserver/users/auth/ldap/callback.

To be honest I'm not sure if this is being covered by rails automagic everywhere else, or jboss/glassfish magic, but it's causing issues with omniauth. Does anyone know of an elegant way to fix it?. It works fine in development which isn't put in a subfolder, but doesn't in production and the jboss/glassfish subfolder.

**Comment by aldanor** [comment]
+1, afaik this is still not resolved?
