### ISSUE TITLE
Why no CHANGELOG?

### ISSUE THREAD

**Issue by olivierlacan** [omniauth/omniauth#756]
It's surprising this project doesn't have any CHANGELOG listing important changes across versions. Is there any reason there isn't one? Would you be interested if I started one in a pull request?

PS: I explain [here](http://keepachangelog.com/) why I think this is important.

**Comment by tmilewski** [comment]
I don't disagree with you here. However, moving forward, we'll go ahead and maintain that in GH releases section.
