### ISSUE TITLE
restart rails when developing new strategy?

### ISSUE THREAD

**Issue by andrewarrow** [omniauth/omniauth#759]
Trying to develop a new strategy. Before I make it it's own Gem, I just placed foo.rb in my rails app/models/ directory to play around with code and get it working. Because of the the code in `config/initializers/omniauth.rb`

```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :foo
end
```

I think it loads everything at rails startup. So all changes require a rails restart. Is there a better way to develop a new strategy without needing to restart rails on every change?

**Comment by tmilewski** [comment]
Not exactly. Such is the Rails initialization process.
