### ISSUE TITLE
Devise + OmniAuth + Doorkeeper  , cannot pass language parameter

### ISSUE THREAD

**Issue by erwin16** [omniauth/omniauth#764]
environment server :  Rails 4.1.4 / Devise 3.2.4/ Doorkeeper 1.4.0
)environment client :  Rails 4.1.4 / Devise 3.2.4 + OmniAuth
I am trying to pass the client app current locale  to my remote API server wo any success

when I perform the remote call, the locale parameter is automatically in the url  ...

```
<a href="/users/auth/doorkeeper?locale=fr">Se connecter à MyServer</a>
console : 
Started GET "/users/auth/doorkeeper?locale=fr" for 127.0.0.1 at 2014-08-14 23:25:59 +0200
```

I, [2014-08-14T23:25:59.717001 #19812]  INFO -- omniauth: (doorkeeper) Request phase initiated.

and I added the following configuration in the devise initializer : 

```
       require 'omniauth/strategies/doorkeeper'
      config.omniauth :doorkeeper,  Rails.application.secrets.doorkeeper_app_id,   Rails.application.secrets.doorkeeper_app_secret, 
      :client_options =>  {
            :site => Rails.application.secrets.doorkeeper_url,
           :authorize_params =>{:lang => I18n.locale}  # :fr 
       }
```

my doorkeeper strategy is : https://gist.github.com/erwin/556eac83ad4e8988494d

unfortunatly , the remote server does not receive any language or locale parameter ( which I need to display the localized sign in form )
in the server console , i cannot see the locale parameter in the url:  

```
Started GET "/oauth/authorize?client_id=9960df759869ff49a73ef25074d1615bd8829bb6932b2f7201dc55ca31ce79d3&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fusers%2Fauth%2Fdoorkeeper%2Fcallback&response_type=code&state=c5d6b1d2ee0d25a0a62aaf416dd5a6b9f1b2016f6ffbf104"
```

the request is processed by my CustomAuthorizationsController#new, but I cannot capture any locale ..

```
    Processing by CustomAuthorizationsController#new as HTML
  Parameters: {"client_id"=>"9960df759869ff49a73ef25074d1615bd8829bb6932b2f7201dc55ca31ce79d3", "redirect_uri"=>"http://localhost:3000/users/auth/doorkeeper/callback", "response_type"=>"code", "state"=>"c5d6b1d2ee0d25a0a62aaf416dd5a6b9f1b2016f6ffbf104"}
Completed 401 Unauthorized in 833ms
Started GET "/users/sign_in" for 127.0.0.1 at 2014-08-14 23:26:02 +0200
Processing by Devise::SessionsController#new as HTML
```

What should be the best way to handle the locale parameter ? 

thanks for help

**Comment by tmilewski** [comment]
The best way might be to store this data in a session and retrieve it on the other end.
