### ISSUE TITLE
Weird issue with periods on SFDC access tokens

### ISSUE THREAD

**Issue by sb8244** [omniauth/omniauth#776]
I opened this PR https://github.com/realdoug/omniauth-salesforce/pull/13 to bypass what I believe is an issue with the body of requests coming from POST in OA. The previous way to do SFDC access token exchange was in the body of POST. This fails sometime. From what I can tell, it only fails when `.` is in the access token. I'm not sure if OA is encoding in some way because there library is deep and I have limited time now.

I would be happy to raise this to SFDC if it isn't an OA issue.

**Comment by tmilewski** [comment]
Appears to have been fixed via `omniauth-salesforce`.
