### ISSUE TITLE
[Question] Building Ubuntu Omniauth Strategy

### ISSUE THREAD

**Issue by kkirsche** [omniauth/omniauth#788]
Hey,
I'm trying to build a strategy for ubuntu which was requested. Using things like curl and whatnot, it's easy to get the token / info but I've been beating my head against a wall with omniauth.

I've tried to setup a basic app in sinatra:

``` ruby
begin
  require 'sinatra'
  require 'omniauth'
  require_relative 'ubuntu.rb'
rescue LoadError
  require 'rubygems'
  require 'sinatra'
  require 'omniauth'
  require_relative 'ubuntu.rb'
end

use Rack::Session::Cookie
use OmniAuth::Builder do
  provider :ubuntu, 'email', 'password'
end

get '/' do
  <<-HTML
  <form action='/auth/ubuntu' method='post'>
    <input type='text' name='email'/>
    <input type='password' name='password'/>
    <input type='submit' value='Sign in with Ubuntu One'/>
  </form>
  HTML
end

# Support both GET and POST for callbacks
%w(get post).each do |method|
  send(method, "/auth/:provider/callback") do
    env['omniauth.auth'] # => OmniAuth::AuthHash
  end
end
```

Which includes my example strategy:

``` ruby
require 'omniauth'

module OmniAuth
  module Strategies
    class Ubuntu
      include OmniAuth::Strategy

      option :fields, [:email, :password]
      option :uid_field, :email

      option :site, 'https://login.ubuntu.com/api/v2/tokens/oauth'

      uid do
        request.params[options.uid_field.to_s]
      end

      info do
        options.fields.each_with_object({}) do |hash, field|
          hash[field] = request.params[field]
          hash
        end
      end
    end
  end
end

```

I'm having a real hard time though. All I want to do is collect the email and password provided, send it as json to the Ubuntu login endpoint and process the result for use by omniauth.

On success, I'd expect to get back:

```
HTTP/1.1 201 CREATED
Content-Type: application/json
Location: /api/v2/tokens/oauth/the-key

{
  "href": "https://login.ubuntu.com/api/v2/tokens/oauth/the-key",
  "token_key": "token-key",
  "token_secret": "token-secret",
  "token_name": "token-name",
  "consumer_key": "consumer-key",
  "consumer_secret": "consumer-secret"
  "date_created": "2013-01-11 12:43:23",
  "date_updated": "2013-01-11 12:43:23"
}
```

Any help would be appreciated as this should be a simple strategy to add but omniauth doesn't seem very clear to me thus far as a new user of it.

**Comment by kkirsche** [comment]
Bump, is there a base config / example project we can use to bootstrap development of OmniAuth strategies

**Comment by tmilewski** [comment]
The point of oauth is that you're not exposing your user credentials to the third-party application.

I haven't tried this code but here's another implementation of an Ubuntu Oauth login: https://github.com/masterkain/omniauth-ubuntu/blob/master/lib/omniauth-ubuntu.rb

As for examples, I'd take a look at other implementations. Some of them are pretty straightforward:
- https://github.com/tmilewski/omniauth-uber/blob/master/lib/omniauth/strategies/uber.rb
- https://github.com/intridea/omniauth-github/blob/master/lib/omniauth/strategies/github.rb
- https://github.com/tmilewski/omniauth-venmo/blob/master/lib/omniauth/strategies/venmo.rb
