### ISSUE TITLE
Mocking Failure error

### ISSUE THREAD

**Issue by korody** [omniauth/omniauth#789]
Hello there. I'm having issues when mocking omniauth failures on my tests. Using Ruby 2.2 and Rails 4.2 with Minitest::Unit 5.5.1.  

I believe I should be getting a failure response but instead I get this test error:
`NoMethodError: undefined method `provider' for :invalid_credentials:Symbol`

I would appreciate any guidance. Thanks!

**Comment by tmilewski** [comment]
Considering that this issue is over two years old, I'm going to close for now. Feel free to re-open should you need to follow-up.

**Comment by rddm2bb** [comment]
@tmilewski  I'm getting the same error, any solution?
