### ISSUE TITLE
Add ability to create auth_hash based on existing auth token

### ISSUE THREAD

**Issue by dyatlov** [omniauth/omniauth#794]
Given:
I already have application which uses omniauth and fills some data based on auth_hash.

Problem:
We created API for our application and ready to work access_token is being sent to application. So after checking that token is correct we want to create user based on information we've got from social network (Facebook).
In order to keep code clean we want to create the same auth_hash which OmniAuth returns in @env. But it is tricky to mimic auth_hash filling from every social network.
Would be good to have a function which would return auth hash based on provider and raw data.

**Comment by tmilewski** [comment]
This is already possible through https://github.com/omniauth/omniauth#integrating-omniauth-into-your-application
