### ISSUE TITLE
Feature request: Two-factor auth

### ISSUE THREAD

**Issue by nileshtrivedi** [omniauth/omniauth#800]
It would be nice if we could enable two-factor auth with two OmniAuth strategies. Possible by bridging first strategy's callback phase to second strategy's request phase?

A practical usecase would be: email/password as the first strategy and SMS-verification as the second.

**Comment by tmilewski** [comment]
Two-factor auth, in terms of OAuth, is already handled by the provider.

Doing this in terms of email/password would fall outside of the scope of OmniAuth. You'd be better served using Devise to accomplish this.
