### ISSUE TITLE
Add something like `env["omniauth.headers"]`

### ISSUE THREAD

**Issue by waiting-for-dev** [omniauth/omniauth#804]
In the same way that params are kept in `env['omniauth.params']`, it would be desirable to keep headers in `env['omniauth.headers']`.

I'm trying to implement multiple providers. The problem is that I'm not using a cookie based authentication system, but a token one, where users are sending their credentials in the request headers each time.

The problem is that I loose that credentials when the user goes back to my app from the provider.

For example, say a user calls `/auth/github` with its credentials in the headers. Then, from `/auth/:provider/callback` I can't retrieve them so I can't say if the user was logged in or not.

It would be great if omniauth had some way to keep headers info, and adding `env['omniauth.headers']' seems the most natural for me .

Thanks

**Comment by TravisTam** [comment]
this is what I am looking for. I am using token auth too but cannot check whether it's request header

**Comment by waiting-for-dev** [comment]
@TravisTam I submitted a pull request which implements it:

https://github.com/intridea/omniauth/pull/806

It is still pending to review.
