### ISSUE TITLE
No Route Matches [GET] "/users/auth/linkedin"

### ISSUE THREAD

**Issue by peyterkim** [omniauth/omniauth#807]
Here is my link:

``` Haml
= link_to %{<i class="fa fa-linkedin"></i>}.html_safe, '/users/auth/linkedin', :class => "btn btn-social-icon btn-linkedin"
```

**/config/initializers/omniauth.rb**

``` Ruby
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :developer unless Rails.env.production?
  provider :linkedin, "key", secret"
  provider :google_oauth2, "key", "secret"
end
```

**/config/routes.rb**

``` Ruby
  devise_for :users
  match '/users/auth/:provider/callback' => 'sessions#create', via: [:get, :post] #This is the only route concerning OAuth
```

It says in the docs that just redirecting the user to '/users/auth/linkedin' should just work but obviously I'm getting an error.

I also tried adding this to my routes.rb

``` Ruby
match '/users/auth/:provider' => 'sessions#passthru', via: [:get, :post]
```

with the passthru method in my SessionsController

Tried so many solutions online but none of them work. HELP!!

**Comment by Nekromancer** [comment]
You probably need to add linkedin to your model like
:omniauthable, :omniauth_providers => [:linkedin]

**Comment by allcentury** [comment]
Next time share the error, it would probably help the people responding to your issue. OmniAuth expects the path to be at `/auth/:provider` unless you specify it elsewhere using `prefix_path`.  So either rename your route or use `prefix_path`.

**Comment by tmilewski** [comment]
☝️ 👍 😄
