### ISSUE TITLE
ActionController::InvalidAuthenticityToken with Gitlab Omnibus 7.11 and custom Omniauth provider

### ISSUE THREAD

**Issue by FredericPoitras** [omniauth/omniauth#813]
So, I created a simple Omniauth provider using the Omniauth Form Builder. Im always getting the same error : ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken). I tried many things like adding an hidden field named "authenticity_token" to the form and giving it the values of session[:_csrf_token], but nothing works. Anyone here knows something about this issue?

**Comment by tmilewski** [comment]
Feel free to re-open using the following template: https://raw.githubusercontent.com/omniauth/omniauth/master/.github/ISSUE_TEMPLATE.md
