### ISSUE TITLE
Access-Control-Allow-Origin' header isn't passed

### ISSUE THREAD

**Issue by urbanvikingr** [omniauth/omniauth#814]
Please I hope that someone can help to resolve this issue.

```
XMLHttpRequest cannot load http://localhost:3000/api/auth/google_oauth2. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.
```

I run a React app using $.ajax from localhost:8080 (auth/:provider) via a Rails API on localhost:3000.

I can run localhost:3000/auth/:provider from browser successfully, but I'm getting the error above.

I've also created a ticket on stackoverflow with more details:
http://stackoverflow.com/questions/31032474/csrf-issue-with-rails-4-omniauth-facebook-rack-cors

I added following code into application.rb:

```
    config.action_dispatch.default_headers = {
      "Access-Control-Allow-Origin" => "*",
      "Access-Control-Request-Method" => "*",
      "Access-Control-Allow-Methods" => "POST, PUT, DELETE, GET, OPTIONS",
      "Access-Control-Allow-Headers" => "Origin, X-Requested-With, Content-Type, Accept, Authorization",
      "Access-Control-Max-Age" => "1728000",
      "X-Frame-Options" => "http://localhost"
    }
```

**Comment by seivan** [comment]
Hmm I need to use OmniAuth with React as well, but I didn't actually think that would work. I suspect you need to do a redirect to the omniauth, but I could be wrong.

**Comment by tmilewski** [comment]
This does not appear to be an OmniAuth issue.
