### ISSUE TITLE
Don't let the project starve

### ISSUE THREAD

**Issue by vemv** [omniauth/omniauth#824]
Hi,

unfortunately one can start seeing the project as unmaintained. For me that's enough reason to not install the gem for new Rails projects.

I understand that keeping the project healthy (with commits, documentation, etc.) is costly. However there is a set of cheap things which you can do immediately, and that would be undoubtedly appreciated.
- Let clearly know what the project status is. After 6 months w/o commits, is it dead? Do you intend to maintain it again soon?
- In case you cannot maintain it anymore, let the community know of our options (can one volunteer as maintainer?)
- Close most issues out there: arbitrary feature requests, unreproducible bugs, real-but-abandoned-issues, requests for free support, have no place in a healthy issue tracker.

Maybe you can look into https://www.bountysource.com/.

Cheers - Victor

**Comment by johnpaulashenfelter** [comment]
👍  was getting ready to submit a change for the developer strategy but looks like I should just manage it myself?

What's going on @intridea-shared @intridea-bot
