### ISSUE TITLE
CSRF token miss match after login using twitter in new browser tab by using copy past a url .

### ISSUE THREAD

**Issue by shekharbora** [omniauth/omniauth#827]
i am using gem 'omniauth' and gem "devise", "~> 2.2.1"  , when i login through twitter successfully login , but after that i copy and past a url its goes logout . i thought its bcz of csrf token miss match .please help me out .

**Comment by tmilewski** [comment]
Without knowing more, this appears to be an issue with your implementation of Devise. Closing for now.
