### ISSUE TITLE
Auth hash schema change: Add groups and roles fields

### ISSUE THREAD

**Issue by tomilaine** [omniauth/omniauth#832]
Hi,

There's sometimes a need to get also information regarding the groups and roles of the user. I imagine this is a pretty common case.

Since there are no fields currently for these in the auth hash schema, different strategies end up returning them in different parts of the auth hash (or it just ends up in raw_data in different formats). I've come across this now with LDAP and SAML.

I suggest adding `groups` and `roles` to the info part in auth hash schema, https://github.com/intridea/omniauth/wiki/Auth-Hash-Schema as optional fields so that strategies can agree to use the same fields and application side code doesn't have to be written provider specifically for groups and roles.

**Comment by tomilaine** [comment]
I know it's just a wiki edit but I was hesitant to go edit an agreed schema. Should the schema actually be maintained in the repo itself?

**Comment by tmilewski** [comment]
I understand where you're coming from, however, while these fields are common among a few providers we could say the same thing about other fields/providers. If we went this route, we'd find ourselves supporting countless fields. 

In my opinion, this is best left up to the provider gem.

Thanks!
