### ISSUE TITLE
I didnt figure out where defined `@ins` instance variables

### ISSUE THREAD

**Issue by Matrixbirds** [omniauth/omniauth#834]
[![](https://cloud.githubusercontent.com/assets/9990676/12755282/c3e1540a-ca09-11e5-8cea-cd5bf42c31c6.png)](https://github.com/intridea/omniauth/blob/v1.0.3/lib/omniauth/builder.rb#L41)

**Comment by tmilewski** [comment]
Considering that this issue is over a year old and lacking crucial information, I'm going to close for now. Feel free to re-open using [this template](https://raw.githubusercontent.com/omniauth/omniauth/master/.github/ISSUE_TEMPLATE.md) should you need to follow-up.
