### ISSUE TITLE
OmniAuth Community organization

### ISSUE THREAD

**Issue by md5** [omniauth/omniauth#836]
As part of a recent discussion around the maintenance of the `omniauth-saml` provider gem (https://github.com/omniauth/omniauth-saml/issues/67), a new @omniauth organization has been created.

Currently, this organization only houses the `omniauth-saml` gem (moved from `PracticallyGreen/omniauth-saml`), but I wanted to get the thoughts of the OmniAuth maintainers and other members of the OmniAuth user community regarding this change.

I could see it making sense to move some of the `omniauth-*` gems and perhaps `omniauth` itself to this organization, particularly given the "Improved Organization Permissions" functionality that GitHub rolled out in the middle of last year (see this post: https://github.com/blog/2020-improved-organization-permissions). With these permissions, it would be relatively straightforward to have a team per provider or teams that span multiple related providers while still controlling ownership access more strictly.

The last thing I would want to have happen is for anyone to get upset about this new organization, so that's why I'm raising the discussion here. I can't speak on behalf of other contributors to the new @omniauth organization, but I'm sure we all want to do what's best for the OmniAuth user community as a whole.

**Comment by LynnCo** [comment]
I would also be available to help maintain with my spare cycles from helping with Bundler

**Comment by olivierlacan** [comment]
Sounds like a good idea. @sferik thoughts?

**Comment by mbleigh** [comment]
As the progenitor of OmniAuth but someone who should no longer have any say
in its development, I'm in favor :)

**Comment by sferik** [comment]
I’m all for it. What are the next steps to make this happen?

**Comment by bufferoverflow** [comment]
Just let me know which people are the omniauth maintainers and I create a team and add you to the @omniauth group.

**Comment by sferik** [comment]
I think that’s just: @mbleigh, @tmilewski, and me.

**Comment by bufferoverflow** [comment]
Ok, I've invited you and made this team: https://github.com/orgs/omniauth/teams/omniauth-maintainers
Now you should be able to move the repo.

**Comment by sferik** [comment]
@bufferoverflow Done: https://github.com/omniauth/omniauth.

**Comment by sferik** [comment]
@bufferoverflow Hmmm, I just tried to update the homepage in the gemspec but it seems like I lost push access to the repo. Can you please double-check the permissions?

**Comment by md5** [comment]
@sferik I've given the `omniauth-maintainers` team "Admin" access to the `omniauth` repository.

I think it would also be good to make one or more members of the core Omniauth team "Owners" of the `omniauth` organization.

**Comment by md5** [comment]
@sferik I've gone ahead and made you an owner.

**Comment by sferik** [comment]
@md5 👍 I just successfully pushed to the repo: https://github.com/omniauth/omniauth/commit/b9bc3bb9ded2b31466a5888af2b30bb191d8109b.

**Comment by bufferoverflow** [comment]
:+1:  super cool! Thanks @md5 for helping out here!

**Comment by md5** [comment]
@sferik Excellent! Do you want to take care of adding the other OmniAuth committers to https://github.com/orgs/omniauth/teams/omniauth-maintainers?

**Comment by bufferoverflow** [comment]
It's so cool that we did this together!
Do we have an OmniAuth logo that we can add to our omniauth organization account?

**Comment by bufferoverflow** [comment]
Just found that on the wiki, https://github.com/omniauth/omniauth/wiki

![logo](https://camo.githubusercontent.com/a517f54100f7f8407ef82490d236b8d8da9b4af3/687474703a2f2f6f6d6e69617574682e6769746875622e696f2f6f6d6e69617574682f696d672f6c6f676f2e706e67)

Is this the official logo?

**Comment by olivierlacan** [comment]
I believe it is. It would be nice if someone from Intridea could provide the source file. Or I could try to redraw it as an SVG.

**Comment by bufferoverflow** [comment]
I've added the logo to the omniauth organization account.

**Comment by md5** [comment]
I think this can be closed.

**Comment by tmilewski** [comment]
Agreed, closing now.
