### ISSUE TITLE
Bug in OmniAuth::Utils.camelize

### ISSUE THREAD

**Issue by rocketblr** [omniauth/omniauth#838]
Hi there,

The method throws an exception when calling it with the 2nd parameter `false`:
`OmniAuth::Utils.camelize(provider, false)`
`NoMethodError - undefined method 'first' for :facebook:Symbol`

Should be an easy fix with adding `.to_s` like 2 lines above.

Thanks!

**Comment by tmilewski** [comment]
I can't recreate this issue. I'll require more information.

Closing for now. If this is still problematic please feel free to re-open the issue. 

Thanks!

**Comment by rocketblr** [comment]
Still happens in 1.5.0:
OmniAuth::Utils.camelize(:facebook, false)
NoMethodError: undefined method `first' for :facebook:Symbol

**Comment by tmilewski** [comment]
Your issue is that it's a symbol or that the use of `false`.

It's that you're not adding the camelization via this method:
`OmniAuth.config.add_camelization('oauth', 'OAuth')`

See: https://github.com/omniauth/omniauth/blob/e919068ec5078bce2dd503c989f2f75023664954/spec/omniauth_spec.rb#L137

**Comment by rocketblr** [comment]
https://github.com/plataformatec/devise/blob/master/app/views/devise/shared/_links.html.erb
Here is a default view provided by devise. `resource_class.omniauth_providers` returns symbols.
The method below accepts the 2nd parameter with the obvious name `first_letter_in_uppercase`:
```
def camelize(word, first_letter_in_uppercase = true)
      return OmniAuth.config.camelizations[word.to_s] if OmniAuth.config.camelizations[word.to_s]

      if first_letter_in_uppercase
        word.to_s.gsub(%r{/(.?)}) { '::' + Regexp.last_match[1].upcase }.gsub(/(^|_)(.)/) { Regexp.last_match[2].upcase }
      else
        word.first + camelize(word)[1..-1]
      end
    end
```
So I needed to have "Sign in with facebook", not "Sign in with Facebook", I passed false and ended up with the error message. That's it.

I just think that I did everything in a pretty straight-forward way and caught the error. If you believe that it's working fine, then feel free to close this issue.

**Comment by rocketblr** [comment]
I wonder if it's okay to use three times earlier in this method `word.to_s`, but not okay to use it 4th time. If you expect to receive strings, then it should fail on every symbol passed. If you expect to receive both symbols and strings, then it should work well with both in all cases. That way it will be consistent, won't it?
