### ISSUE TITLE
Forbidden error after succesful callback

### ISSUE THREAD

**Issue by gawin** [omniauth/omniauth#842]
I'm trying to setup Omniauth for Google, Facebook and Linkedin.

After the callback url is called a **Forbidden** page is shown.

This always happens the first time a user authenticates. The second time a user authenticates the user does successfully get redirected without a **Forbidden** page.

I have no idea where this **Forbidden** page is triggered, and how to resolve it. The strange thing is that even if the **Forbidden** page is shown, the user does successfully authenticate! This can be verified by the credentials that are stored in a local session in the callback before the **Forbidden** error is thrown.

This is the code I'm using:
https://github.com/gawin/oauth-test

And this the test site I've made for this issue:
https://oauth.teamily.com

_Any help or suggestions would be more than appreciated!_

```
Gems included by the bundle:
  * bundler (1.11.2)
  * byebug (8.2.2)
  * encrypted_cookie (0.0.4)
  * faraday (0.9.2)
  * hashie (3.4.3)
  * jwt (1.5.1)
  * multi_json (1.11.2)
  * multi_xml (0.5.5)
  * multipart-post (2.0.0)
  * oauth2 (1.1.0)
  * omniauth (1.3.1)
  * omniauth-facebook (3.0.0)
  * omniauth-google-oauth2 (0.3.1)
  * omniauth-linkedin-oauth2 (0.1.5 09e0b99)
  * omniauth-oauth2 (1.4.0)
  * puma (3.1.0)
  * rack (1.6.4)
  * rack-protection (1.5.3)
  * sinatra (1.4.7)
  * tilt (2.0.2)
```

![screen shot 2016-03-08 at 14 03 33](https://cloud.githubusercontent.com/assets/25894/13603639/97ac46cc-e536-11e5-92a5-1edc62fab79b.png)

**Comment by gawin** [comment]
Any ideas?

**Comment by FanaHOVA** [comment]
I'm getting the same issue, bumping this.

**Comment by tmilewski** [comment]
This appears to be outside of the OmniAuth scope. At no point does OmniAuth return 403.
