### ISSUE TITLE
Crawler accessing /auth/failure

### ISSUE THREAD

**Issue by joker-777** [omniauth/omniauth#844]
Hi guys,

just wanted to check if you have experienced it too that crawler find out about `/auth/failure` and access it randomly. Do you just ignore them?

Thanks!

**Comment by anlek** [comment]
I'm not sure about the random, but version `1.4` was preventing login via doorkeeper. Had to downgrade to `1.3.1` and it just worked.

**Comment by tmilewski** [comment]
I haven't specifically seen it. That said, it shouldn't really be an issue. You could try setting up a `robots.txt` file to prevent this overall.
