### ISSUE TITLE
CSRF Protection bypassed 

### ISSUE THREAD

**Issue by bewithsahilsaif** [omniauth/omniauth#851]
Hi, 

I found a CSRF issue with omniauth

Following the request link for login into forum after the authorization from auth-client-getpebble.com

https://forums.host.com/auth/oauth2_basic/callback?code=261b8f5d8a998d19124107b8dd1d74d6f0088168577d02576325f0cb3b9dbd14&state=75f3a680522122b3683d6984000e4fd3310f41f8d13bf857

See, Above endpoint is protected from the CSRF issue which a verification token named as "State". 

But,. 

The endpoint does not check the presence of the state token during login. 

After can easily bypass the issue by just deleting the state token from the GET request. 

So, 

Final bypass for this CSRF protection will look like. 

https://forums.host.com/auth/oauth2_basic/callback?code=261b8f5d8a998d19124107b8dd1d74d6f0088168577d02576325f0cb3b9dbd14&state=

Please fix this issue by validating the state token properly before allowing login. 

Please also let me know anything you need to know about this issue. 

Thanks 
Sahil

**Comment by bewithsahil002** [comment]
Hello, 

Can i get the update on this issue ?

**Comment by tmilewski** [comment]
This isn't a direct issue with the Omniauth gem but rather potentially one with the `omniauth-oauth2` gem.

I'd suggest filing this issue there. Apologies for the delay.
