### ISSUE TITLE
uninitialized constant OmniAuth::Strategies::LinkedIn::MultiJson error in Rails 5

### ISSUE THREAD

**Issue by Mingus85** [omniauth/omniauth#852]
Hi,

after being redirected from Linkedin to my `OmniauthCallbacksController < Devise::OmniauthCallbacksController` I get the following error:

`uninitialized constant OmniAuth::Strategies::LinkedIn::MultiJson`

Is this an omniauth issue, or did I do something wrong. Is there a remedy?

Seperately installing the multijson gem does not seem to solve it.

**Comment by tmilewski** [comment]
Considering "`OmniAuth::Strategies::LinkedIn::MultiJson`" and the fact that Omniauth core doesn't use `multijson` I'm going to suggest that you reach out on the `omniauth-linkedin` repo.

Thanks!
