### ISSUE TITLE
Show login as root_url for unauthenticated - Rails 5

### ISSUE THREAD

**Issue by duffyjp** [omniauth/omniauth#853]
I came up with the following seemingly simple solution to show the my login page at the root_url instead of /login for unauthenticated users.  I'd like input on security considerations.

This is a Rails 5 only solution, as it defined two root urls-- a new feature.

config/routes.rb

``` ruby
root :to => "sessions#new", constraints: -> (request) { request.session[:user_id].blank? }
root :to => "home#index"
```

This works perfectly but seems too easy.

**Comment by tmilewski** [comment]
This, to me, doesn't seem too secure.

I would suggest using `Devise` and doing something like this: https://github.com/plataformatec/devise/wiki/How-To:-Define-resource-actions-that-require-authentication-using-routes.rb

**Comment by duffyjp** [comment]
@tmilewski care to elaborate on your security concerns?
