### ISSUE TITLE
Potentially incorrect dependency specification

### ISSUE THREAD

**Issue by acoffman** [omniauth/omniauth#860]
Hi!

I seem to be running into an issue with the `hashie` dependency of omniauth. Bundler is resolving to the latest version of hashie `3.4.5` which does not appear to be compatible with omniauth. Attempting to load any strategy results in `NameError: uninitialized constant Hashie::Extensions::Array`. Hashie `3.4.2` on the other hand, works just fine.

It seems like upstream, there shouldn't have been breaking changes in a `0.0.x` point release, but in the meantime, constraining the specified version in the omniauth gemspec would fix the immediate issue.

Thanks for a great project!

**Comment by acoffman** [comment]
Seems like this issue is being addressed here: https://github.com/intridea/hashie/issues/367 and but this PR here: https://github.com/omniauth/omniauth/pull/859

**Comment by medright** [comment]
Agreed, this issue snagged me as well

**Comment by dblock** [comment]
I released hashie 3.4.6 so this can be closed.
