### ISSUE TITLE
Problems in macOS Sierra

### ISSUE THREAD

**Issue by thiagok** [omniauth/omniauth#861]
People, help me please. Today I updated my MacBook Pro to the new version of Mac. I got this error on started my application (passenger start, rails s, puma, ...):

```
[ 2016-09-23 14:54:29.3122 36954/0x70000e363000 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /Users/klein/Code/rails/artia-app: An error occurred while starting up the preloader.
  Error ID: 3e3de1d0
  Error details saved to: /var/folders/h0/vhs_g11j66z3b9t6bsg_cj_m0000gn/T//passenger-error-4Fw7Ey.html
  Message from application: There was an error while trying to load the gem 'omniauth'.
Gem Load Error is: uninitialized constant OmniAuth::Configuration::Form
```

**Please check this Gist with the backtrace:** https://gist.github.com/thiagok/5a2b0083057f74ba8cac471ed73fea06

**Comment by tmilewski** [comment]
Going to close this out but, if this is still an issue, please feel free to reopen and ping me.
