### ISSUE TITLE
Facebook omniauth: Ensure unique username

### ISSUE THREAD

**Issue by kerensei** [omniauth/omniauth#862]
I have a ruby on rails app with user authentication with devise + omniauth.
In my User model I want to ensure that the user.name is unique, so that there are no duplicate usernames in my app.

After looking around I came up with the following code:

**User.rb**

      validates :name, presence: true, uniqueness: true, length: {minimum: 6, maximum: 30}

      def ensure_username_uniqueness
        uniqname = (self.name).dup     
        num = 1
        until(User.find_by(name: uniqname).nil?) do ## returns true, should be false ##
          uniqname = self.name+"-#{num}"    
          num += 1
        end    
        self.name = uniqname      
      end  

      private  
  
      def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
          user.provider = auth.provider
          user.uid = auth.uid        
          user.email = auth.info.email
          user.password = Devise.friendly_token[0,20]
          user.name = auth.info.name[0..29].downcase.gsub(" ", "-")
          user.ensure_username_uniqueness           
          user.remote_avatar_url = auth.info.image
          user.skip_confirmation!
        end
      end   

When I test Facebook registration with a name that already exists in the database, I get redirected to the sign up page (meaning sign up failed). 

I set a binding.pry and noticed that the 'until' loop doesn't get executed since it returns true (even though the name already exists). I can't seem to understand why the loop does not get executed. 

Any help would be much appreciated!

**Comment by marekciupak** [comment]
> the 'until' loop doesn't get executed since it returns true (even though the name already exists)

@kerensei I think `User.find_by` does not return anything, because your new user is not saved in the db yet.

**Comment by kerensei** [comment]
update: 
After setting a break point in the code before entering the loop, I found that there are no user records (User.all = []). my guess is that is has to do with devise/omniauth configuration. Any ideas? 10x

**Comment by tmilewski** [comment]
Without digging deep, maybe try `.exists?` rather than `nil?`. 

Using something like [friendly_id](https://github.com/norman/friendly_id) might be a better, and cleaner, approach overall.

---

Sorry to do this,  I'm going to have to close this as it's not an issue with Omniauth.
