### ISSUE TITLE
Push omniauth 1.4.3 to rubygems

### ISSUE THREAD

**Issue by stanhu** [omniauth/omniauth#893]
Would you mind also pushing omniauth 1.4.3 to Rubygems? https://rubygems.org/gems/omniauth/versions/ shows 1.4.2.

**Comment by tom-lord** [comment]
Still an issue. There is a [tagged release for `v1.4.3`](https://github.com/omniauth/omniauth/releases/tag/v1.4.3), but it's [not on RubyGems](https://rubygems.org/gems/omniauth/versions).

This is especially useful for anyone (unfortunately) still running ruby version `<= 2.1.8`, as the ruby version requirement was added to `v1.5.0` of this gem.

**Comment by sshaw** [comment]
Just had this issue too. 

`git checkout v1.4.3 && rake release`

😿

**Comment by tmilewski** [comment]
https://rubygems.org/gems/omniauth/versions/1.4.3
