### ISSUE TITLE
Support for OAuth2? 

### ISSUE THREAD

**Issue by Erowlin** [omniauth/omniauth#895]
It's not quite clear in the documentation, I'm almost certain at 100% that this gem is only for **OAuth1**, is it the case ? 
If yes, do you have any substitute for OAuth2? I will do a PR to update the README to clarify that important point. 

Thank you!

**Comment by tmilewski** [comment]
https://github.com/intridea/omniauth-oauth2

**Comment by tmilewski** [comment]
`omniauth` is the core lib and `omniauth-oauth2` is built off of that. Likewise, gems requiring OAuth2 are built off of `omniauth-oauth2`. Ex: `omniauth-facebook` and `omniauth-github`.
