### ISSUE TITLE
using omniauth with mobile flow

### ISSUE THREAD

**Issue by avdovin** [omniauth/omniauth#897]
Hi!
How to use access token received from mobile app in omniauth? 

PS Omniauth already exist in the project and don't want duplicate functionality

**Comment by tmilewski** [comment]
If you already have the token via the mobile app, Omniauth is somewhat irrelevant. What exactly are you trying to do?

**Comment by avdovin** [comment]
Omniauth in the mobile flow i want use to obtain user data from different social networks (this part already configured and working on website), while part associated with obtaining a access token is more convenient to do natively with SDK

**Comment by tmilewski** [comment]
So, if you have the access tokens, you don't need to use Omniauth. Pass the tokens back to your API and use said tokens to request the data from whichever social network.

Do note though that the root credentials you're using to retrieve tokens and request data must match between your mobile app and site.
