### ISSUE TITLE
Applying additional oauth scopes in the initializer

### ISSUE THREAD

**Issue by d00medman** [omniauth/omniauth#904]
Please complete all sections.

### Configuration

- Provider Gem: `omniauth-coinbase`
- Ruby Version: `2.3.1`
- Framework: `5.0.4`
- Platform: `Mac Os`

### Actual Behavior

I am trying to leverage the wallet:transactions:send. I am able to use all scopes and access the API as usual, but the send functionality requires additional parameters. When I attempt to access coinbase, I am given a screen which displays the error `Invalid amount for meta[send_limit_amount]`. From my research, I have found that I need to construct an authorization URL that looks like this

```shell
https://www.coinbase.com/oauth/authorize?response_type=code
&client_id=9ade8a928f9d394f4ce916651fdbd26c6b541351ba5a20b3687facb891278059
&redirect_uri=https%3A%2F%2Fwww.coinplug.com
&scope=wallet:user:read,wallet:accounts:read,wallet:transactions:transfer,wallet:transactions:request,wallet:transactions:read,wallet:transactions:send
&meta[send_limit_amount]=10
&meta[send_limit_currency]=USD
&meta[send_limit_period]=day
```
but I have really no idea where I would do this or how I would phrase it

### Steps to Reproduce

I know that my attempt to connect to the API is not even making it to the sessions controller. Here is my initializer:

```ruby
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :coinbase, ENV['CLIENT_ID'], ENV['CLIENT_SECRET'],scope: 'wallet:user:read wallet:user:email wallet:accounts:read wallet:transactions:send'
end
```
I assume that I need to apply the required meta parameters in this initializer, but I am not sure of the syntax. I really need help on this, it seems like no one on the internet has the answer to this question, and it is extremely frustrating.

**Comment by d00medman** [comment]
resolved with following changes to initializer:

```ruby
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :coinbase, ENV['CLIENT_ID'], ENV['CLIENT_SECRET'],
  scope: 'wallet:user:read wallet:user:email wallet:accounts:read wallet:transactions:send',
  :meta => {'send_limit_amount' => 1}
end
```

**Comment by tmilewski** [comment]
Glad you got it figured out!
