### ISSUE TITLE
mock_auth doesn't redirect to success url with rspec 3.7.0

### ISSUE THREAD

**Issue by anaumov** [omniauth/omniauth#918]
### Configuration

- Provider Gem: `omniauth-1.7.1`
- Ruby Version: `2.4.2p198`
- Framework: `rails (5.1.4)`
- Platform: `mac`

### Expected Behavior

When using mock_auth I expect to all requests to twiiter API will redirected to success url immediately.

### Actual Behavior

After updating to rspec 3.7.0 mock_auth stops intercept requests to twitter API. It prompt twitter form to user (capybara).

### Steps to Reproduce

use rspec 3.7.0 with capybara and omniauth.

**Comment by juno** [comment]
@anaumov 
I faced same issue and it fixed with modify puma config like this:

```ruby
# config/puma.rb
if Rails.env.test?
  # Disable cluster mode while test
  workers 0
else
  workers ENV.fetch('WEB_CONCURRENCY') { 2 }
end
```

Hope this helps.
