### ISSUE TITLE
Any way to get the url that is generated in OmniAuth::Strategies::Strategies#request_phase

### ISSUE THREAD

**Issue by homerlex** [omniauth/omniauth#919]
For various reasons I need the direct link to the auth provider from my rails app.  I cannot send the user to myapp/users/auth/<provider> and have them redirected.  What I need (in my erb view) is the url that gets generated when OmniAuth::Strategies::Strategies#request_phase is called.

Is there some reasonable way to get this url, for a given provider, from a rails view (or controller)?

**Comment by tmilewski** [comment]
While I wouldn't suggest it, the only real way would be to write a provider gem to handle (read: hack around) this.

https://github.com/omniauth/omniauth/blob/master/lib/omniauth/strategy.rb#L321-L326
https://github.com/omniauth/omniauth-instagram/blob/478e069b82142fab78e8611fc01331a967353ee8/lib/omniauth/strategies/instagram.rb#L14-L20
https://github.com/intridea/omniauth-oauth2/blob/464fcef6c0a5f1a7526b9701cec37f342ce57ae3/lib/omniauth/strategies/oauth2.rb#L47-L49
