### ISSUE TITLE
Website is down?

### ISSUE THREAD

**Issue by chancancode** [omniauth/omniauth#926]
Hello! The repo description links to the website – https://omniauth.io, but that seems to be down (it's a "password protected site").

**Comment by tmilewski** [comment]
The original website has been down for a while. It was managed by the old maintainers. A new one is being created but it's not there yet.

**Comment by chancancode** [comment]
Should that link be removed for now?

**Comment by optimista** [comment]
Just found about this. Wanted to access the website. It's still like that.
Quoting: "Password protected site \n Please enter your password to get access."
