### ISSUE TITLE
keycloak support

### ISSUE THREAD

**Issue by nmenag** [omniauth/omniauth#928]
i was  doing an integration for **keycloak**  and used a this gem https://github.com/jjbohn/omniauth-openid-connect, but this gem has some problems.  It would be great to use it from omniauth. 

Keycloak is connect via **openid_connect**

my connection was with `omniauth 1.1` and `Devise 4.4` with `Rails 5.1`, `ruby 2.4.2.`. using the `strategy`  from the `omniauth-openid-connect` with `openid_connect 1.0.`

**Comment by tmilewski** [comment]
We don't maintain `omniauth-openid-connect` but it appears that that's an unmaintained version. Please check out: https://github.com/m0n9oose/omniauth_openid_connect
