### ISSUE TITLE
mocking `request.env['omniauth.origin']` when request.

### ISSUE THREAD

**Issue by gnextAungNaing** [omniauth/omniauth#934]
Hi I would like to rspec testing with `request.env['omniauth.origin']`. I successfully mocked `OmniAuth.config.mock_auth[:google_oauth2]`. but I can't set the `request.env['omniauth.origin']` value. The callback controller doesn't know it. How can i do it?

### Configuration

- Provider Gem: `omniauth-google-oauth`
- Ruby Version: `2.4.2`
- Framework: `rails`

### RSpec
```
it 'should redirect to another page' do
      valid_google_oauth2_login_setup
      get '/auth/google_oauth2/callback'
      request.env['omniauth.auth'] = OmniAuth.config.mock_auth[:google_oauth2]
      request.env['omniauth.origin'] = 'http://www.xxxx.com'
end
```

**Comment by jeremyk3** [comment]
There's literally zero documentation on this, but this worked for me:

```
    OmniAuth.config.before_callback_phase do |env|
      env['omniauth.origin'] = 'https://example.com/'
    end
```

**Comment by qnm** [comment]
@jeremyk3 Thanks - however what you suggest affects Omniauth across all specs. Any ideas how to isolate the change to only a particular test?

**Comment by speckins** [comment]
You're setting the request.env values _after_ you've performed the GET request.  You need to set them before you invoke the request.

**Comment by njcameron** [comment]
@jeremyk3 I had the same problem, the work around I came up with was adding in a blank block in the setup e.g.

``` ruby
class OauthTest
  def setup
    # set stuff up
    # ...
    OmniAuth.config.before_callback_phase do |env|
      # intentionally left blank
    end
  end

  test "A when origin is blank" do
    OmniAuth.config.before_callback_phase do |env|
      env['omniauth.origin'] = nil
    end
 
    # test stuff
  end

  test "Another thing" do
    # test other stuff
  end
end

```

**Comment by yshmarov** [comment]
> OmniAuth.config.before_callback_phase do |env|
>       env['omniauth.origin'] = 'https://example.com/'
>     end

I can confirm that this works for me. Thanks a lot! 🙇‍♂️
