### ISSUE TITLE
Testing with omniauth.params ?

### ISSUE THREAD

**Issue by nunosilva800** [omniauth/omniauth#937]
I have an invitation token set as params before the request phase and I want to test the controller behaviour with them.

```
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
# ...
    def google_oauth2
      user = User.from_omniauth(
        request.env['omniauth.auth'],
        request.env['omniauth.params']
      )
# ...
```
This works, but so far I'm not able to set these params in the tests:

```
RSpec.describe 'Users::OmniauthCallbacksController', type: :request do
#...
       before do
          Rails.application.env_config['omniauth.params'] =
            OmniAuth::AuthHash.new(
              invitation_token: invited.invitation_token
            )
        end
 
```

### Configuration

- Provider Gem: `omniauth (1.8.1)`, `omniauth-google-oauth2 (0.5.3)`, `omniauth-oauth2 (1.5.0)`, `devise (4.4.3)`
- Ruby Version: `2.5.1`
- Framework: `Rails 5.2`
- Platform: `Linux`

### Expected Behavior

I'd expect to be able to set the `request.env['omniauth.params']` in a similar wait we set `request.env['omniauth.auth']`, and as indicated in the wiki: https://github.com/omniauth/omniauth/wiki/Integration-Testing

### Actual Behavior

Going into the debugger, the value for `request.env['omniauth.params']` is always `{}` (instance of Hash)

### Steps to Reproduce

N/A

**Comment by GBH** [comment]
This can't be this hard? I ended up mocking the actual auth method:

```
allow(User).to receive(:from_omniauth).and_wrap_original do |method, auth, params|
  method.call(auth, {foo: "bar"})
end
```

Feel like this is something that should be built-in, no?

**Comment by mike1o1** [comment]
I'm not sure if this is still an issue for you, but I ran into trying to test something similar in an integration test. After looking through the OmniAuth code, I noticed that the params are being pulled from the initial GET request to the authorize url and stored in the session. They are then retrieved from the session in the callback phase.

What I ended up doing was making a request to the authorize path with my parameters, and then when I made my second request to the callback phase, they were present.

```ruby
# integration_test.rb
test "can access params" do
  sign_in @user

  # setup my parameters
  get user_google_oauth2_omniauth_authorize_url(from: :settings)

  get user_google_oauth2_omniauth_callback_url
end

# omniauth_callbacks_controller.rb

def google_oauth2
  puts request.env["omniauth.params"] # {"from"=>"settings"}
end
```

**Comment by maxKimoby** [comment]
This is still a problem. Cannot set or access 'omniauth.params' without hacking the code first like they did above.

**Comment by christianrolle** [comment]
I suggest to set up a OmniAuth helper like:

`
# spec/support/omniauth_helper.rb
module Test
  class OmniAuthCallback
    attr_reader :provider

    def initialize(provider)
      OmniAuth.config.test_mode = true
      @provider = provider.to_sym
    end

    def mock(params)
      auth_hash = OmniAuth::AuthHash.new params.update(provider: provider)
      OmniAuth.config.mock_auth[provider] = auth_hash
      Rails.application.env_config['devise.mapping'] = Devise.mappings[:user]
      Rails.application.env_config['omniauth.auth'] = auth_hash
    end
  end
end
`
and use it like:
`
RSpec.describe 'Users::OmniauthCallbacksController', type: :request do
  before do
    Test::OmniAuthCallback.new(:google_oauth2).mock invitation_token: invited.invitation_token
  end
end
`
The good thing about extracting the OmniAuth test setup details into a helper, it reusable for other OmniAuth tests and it abstracts away the boring setup details.

**Comment by ganbootyard** [comment]
I added values to the `omniauth.params` by doing this on a `before :each` block:

```
  before :each do
    request.env["devise.mapping"] = Devise.mappings[:user]
    request.env["omniauth.auth"] = OmniAuth.config.mock_auth[: google_oauth2]
    request.env["omniauth.params"] = { 'invitation_token' => 'YOURTOKENHERE' }
  end
```
Working so far. Maybe this could help.
