### ISSUE TITLE
Generate authorize URL without devise

### ISSUE THREAD

**Issue by husam212** [omniauth/omniauth#946]
Is there a way to generate the authorization URL without using `devise` gem?

**Comment by mehreentahir-16** [comment]
@husam212 Did you find the answer? I'm trying to do something similar but no luck so far

**Comment by AyeRobredo** [comment]
I'm trying to do this. Can you help me? Did they find the way?

**Comment by BobbyMcWho** [comment]
Hi @AyeRobredo have you followed the general instructions on the wiki?

**Comment by husam212** [comment]
The auth URL is `/auth/:provider`, I'm not sure if that helps, I lost the context of this issue.
