### ISSUE TITLE
RACK_ENV vs RAILS_ENV

### ISSUE THREAD

**Issue by danielwheeler1987** [omniauth/omniauth#947]
Is there a reason that in failure_endpoint.rb ...
'
def call
      raise_out! if OmniAuth.config.failure_raise_out_environments.include?(ENV['RACK_ENV'].to_s)
      redirect_to_failure
    end
'
That y'all are using RACK_ENV vs RAILS_ENV. If I set RACK_ENV in a rails app it doesn't seem to respect the value I set.

**Comment by tmilewski** [comment]
It should honor `RACK_ENV`. We don't use `RAILS_ENV` as this is, at its core, a Rack-based middleware. As such, it can be utilized in places other than just Rails.

Are you able to access `RACK_ENV` elsewhere in your application?
