### ISSUE TITLE
This resource is no longer available under v1 APIs

### ISSUE THREAD

**Issue by JDonMc** [omniauth/omniauth#959]
Please complete all sections.

### Configuration

- Provider Gem: `omniauth-linkedin*`
- Ruby Version: `2.5.3`
- Framework: `Rails`
- Platform: `Azure`

### Expected Behavior

Login after given auth credentials

### Actual Behavior

Page loads with:

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

Server logs:

ERROR -- omniauth: (linkedin) Authentication failure! invalid_credentials: OAuth2::Error, :
{
  "errorCode": 0,
  "message": "This resource is no longer available under v1 APIs",
  "requestId": "5VR53ZGOTH",
  "status": 410,
  "timestamp": 1558592555549
}

### Steps to Reproduce

https://sourcey.com/articles/rails-omniauth-using-devise-with-twitter-facebook-and-linkedin

**Comment by BobbyMcWho** [comment]
I believe this is an issue with your version of omniauth-linkedin and not omniauth itself.
