### ISSUE TITLE
What with CSRF?

### ISSUE THREAD

**Issue by AleksandrLeontev** [omniauth/omniauth#967]
Logs:
`[0cd3486a-ff6b-433e-b743-43e5e7e40ea0] (google_oauth2) Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected`

My configs:
`provider :google_oauth2, ENV['GOOGLE_CLIENT_ID'], ENV['GOOGLE_CLIENT_SECRET'], verify_iss: false`

Should I use `provider_ignores_state: true` ?

**Comment by BobbyMcWho** [comment]
Closing this since it's stale, it also may be better suited for the omniauth OAuth2 repo
