### ISSUE TITLE
Maintainers?

### ISSUE THREAD

**Issue by BobbyMcWho** [omniauth/omniauth#978]
As of late, there has been very little activity on submitted issues or PRs, and CI was failing for months. 

@toupeira @tmilewski @md5 @bufferoverflow @supernova32, 

What do you need help-wise here?

I'm willing to help out if that's what you need to keep this project maintained.

**Comment by supernova32** [comment]
@BobbyMcWho thank you for the offer. I do think we need some help reviewing PRs and closing old issues. I'll add you to the maintainers list :)

**Comment by BobbyMcWho** [comment]
Thanks @supernova32, any guidelines around merging, release schedules/cadence etc.?

**Comment by toupeira** [comment]
Just to clarify: I was only working on https://github.com/omniauth/omniauth-http-header for a bit, but that gem never went anywhere :wink: (@bufferoverflow not sure if we should delete the repository?)

I was never involved in the main OmniAuth gem and don't have push access, or time to help, unfortunately.

**Comment by BobbyMcWho** [comment]
Sorry @toupeira, the best I could find were the names on the org 😅
