### ISSUE TITLE
Release v. next

### ISSUE THREAD

**Issue by dblock** [omniauth/omniauth#980]
Please release v. next "as is" or with https://github.com/omniauth/omniauth/pull/979. Currently hahie build [is broken](https://travis-ci.org/hashie/hashie/jobs/612858905) on an integration spec, but we would like to continue ensuring it's not breaking its downstream dependency (omniauth), again, with so many users.

**Comment by BobbyMcWho** [comment]
@mbleigh @tmilewski or @sferik
can you add me to owners on rubygems for omniauth/omniauth please?

**Comment by mbleigh** [comment]
@BobbyMcWho you are now an owner of `omniauth` on RubyGems.

**Comment by BobbyMcWho** [comment]
Released [v1.9.1](https://github.com/omniauth/omniauth/releases/tag/v1.9.1)
