### ISSUE TITLE
[bug] The website is password protected.

### ISSUE THREAD

**Issue by ferreirati** [omniauth/omniauth#986]
### Expected Behavior
The website should be accessible without any authentication.

### Actual Behavior
The website is password protected.
![image](https://user-images.githubusercontent.com/9512604/70076043-bf9dce00-15dc-11ea-9c25-f76e9f5572cf.png)

### Steps to Reproduce

- Open https://www.omniauth.io/

**Comment by BobbyMcWho** [comment]
Duplicate of https://github.com/omniauth/omniauth/issues/933
