### ISSUE TITLE
Website Unavailable

### ISSUE THREAD

**Issue by Winterspite** [omniauth/omniauth#987]
I know this doesn't strictly apply to the omniauth library, but wanted to raise it. I attempted to browse to https://www.omniauth.io/ per your Git repository to read up on the Gem and saw this:

https://i.imgur.com/Hc3Z6r6.png

Not sure if you guys have lost control of the domain or the webserver or what exactly is going on, but it seems not good.

**Comment by BobbyMcWho** [comment]
Duplicate of #933
